name: SDET Bootcamp pipeline

on:
  push:
    branches:
        - main
  pull_Request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build:

    runs-on: Ubuntu-Latest
    strategy:
      matrix:
        dotnet-version: [8.0.x]
        include:
          - dotnet-version: 8.0.x
            framework: net8.0

    steps:
      - uses: actions/checkout@v3

      - name: Setup .Net Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: List installed .NET SDK
        run: dotnet --list-sdks

      - name: Restore Project Dependencies
        working-directory: ./csharp_bootcamp_exercises/SdetBootcampDay1
        run: dotnet restore -p:TargetFramework=${{ matrix.framework }}

      - name: Build the project
        working-directory: ./csharp_bootcamp_exercises/SdetBootcampDay1
        run: dotnet-build --framework ${{ matrix.framework }} --no-restore

      - name: Run Day 1 Tests
        working-directory: ./csharp_bootcamp_exercises/SdetBootcampDay1
        run: dotnet test --framework ${{ matrix.framework }} --no-restore --no-build --verbosity normal --filter Name~Exercises